version: '3.7'

# docker-compose up

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx/core:/etc/nginx/conf.d
            #- ./nginx/core:/etc/nginx/
            # - ./nginx/core/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./nginx/www:/var/www/
            - ./nginx/logs:/var/logs/nginx/
            - ./nginx/html:/usr/share/html/
        ports:
            - "6080:80"
            - "443:443"
        links:
            - php
    php:
        # Билдим с помощью dockerfile указав директорию где он лежит
            build: ./php
            #image: php:7-fpm
            container_name: php-fpm
            volumes:
                - ./nginx/www:/var/www
            ports:
                - "9000:9000"
            links:
                - mariadb
    mariadb:
        image: mariadb
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
            - MYSQL_ROOT_PASSWORD=
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        restart: always
        environment:
            - PMA_HOST=mariadb
        links:
            - mariadb
